name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U testuser;
          do echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run migrations to update db
        run: npm run db:migrate
      - run: npm run test:e2e
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: 'testpassword'
          POSTGRES_DB: testdb
          NODE_ENV: test
